catalogs:
    peer:
        "@eslint-react/eslint-plugin": ^1.43.0
        "@next/eslint-plugin-next": ^15.3.0
        "@unocss/eslint-plugin": ">=0.50.0"
        astro-eslint-parser: ^1.2.2
        eslint: ^9.24.0
        eslint-plugin-astro: ^1.3.1
        eslint-plugin-react-hooks: ^5.2.0
        eslint-plugin-react-refresh: ^0.4.19
        eslint-plugin-solid: ^0.14.5
        eslint-plugin-svelte: ">=2.35.1"
        eslint-plugin-tailwindcss: ^3.18.0
        eslint-plugin-vue: ^9.33.0
        eslint-plugin-vuejs-accessibility: ^2.4.1
        eslint-processor-vue-blocks: ^2.0.0
        svelte-eslint-parser: ">=0.37.0"
        vue-eslint-parser: ^9.4.3
